import type { Metadata } from "next";
import "./globals.css";
import Footer from "@/components/Footer";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import localFont from "next/font/local";

const Sohne = localFont({
  src: "./fonts/TestSohne-Kraftig.otf",
  weight: "100 200 300 400 500 600 800",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${Sohne.className}`}>
        {children}
        <Footer />
        <ToastContainer theme="dark" position="top-right" limit={1000} />
      </body>
    </html>
  );
}
